from django.db import models
from django.contrib.auth.models import User


class ProcessedImage(models.Model):
    """
    Stores background-removed image records for logged-in users.

    Fields:
        user          - ForeignKey to Django's built-in User model
        original_image  - The image uploaded by the user (stored in media/originals/)
        processed_image - The background-removed result (stored in media/processed/)
        uploaded_at     - Timestamp of when the image was uploaded
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='processed_images',
        help_text="The user who uploaded this image."
    )
    original_image = models.ImageField(
        upload_to='originals/',
        help_text="Original image uploaded by user."
    )
    processed_image = models.ImageField(
        upload_to='processed/',
        blank=True,
        null=True,
        help_text="Background-removed image generated by AI."
    )
    prediction_label = models.CharField(
        max_length=120,
        blank=True,
        help_text="Top ImageNet prediction for the uploaded image."
    )
    prediction_confidence = models.FloatField(
        blank=True,
        null=True,
        help_text="Confidence score for the top ImageNet prediction."
    )
    predictions = models.JSONField(
        default=list,
        blank=True,
        help_text="Top ImageNet predictions returned by the classifier."
    )
    uploaded_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when image was uploaded."
    )

    class Meta:
        ordering = ['-uploaded_at']
        verbose_name = 'Processed Image'
        verbose_name_plural = 'Processed Images'

    def __str__(self):
        return f"{self.user.username} — {self.original_image.name} ({self.uploaded_at.strftime('%Y-%m-%d %H:%M')})"
