# Generated by Django 4.2.30 on 2026-05-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Original image uploaded by user.",
                        upload_to="originals/",
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        help_text="Background-removed image generated by AI.",
                        null=True,
                        upload_to="processed/",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when image was uploaded.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who uploaded this image.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Image",
                "verbose_name_plural": "Processed Images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
